import "./globals.css";
import MainHeader from "@/components/header/MainHeader";
import styles from '~/scss/LandingPage/MainPage.module.scss'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Saas Whitepace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.layout_container}`}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
